server:
  port: 8081

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-Prefix, /admin

        - id: registry-service
          uri: lb://registry-service
          predicates:
            - Path=/registry/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=0

        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventories/**
          filters:
            - StripPrefix=0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
