server:
  port: 8083

spring:
  application:
    name: inventory-service

  rabbitmq:
    exchange:
      order: order.exchange
      routing-key:
        order-cancelled: order.cancelled
    listener:
      simple:
        default-requeue-rejected: false
        acknowledge-mode: auto
    template:
      exchange: ${rabbitmq.exchange.order}
    message-converter:
      json:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Dirección del Eureka Server
    register-with-eureka: false
    fetch-registry: false

  instance:
    prefer-ip-address: true
    hostname: localhost
