server:
  port: 8082

spring:
  application:
    name: order-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange:
    order: order.exchange
  routing-key:
    order-created: order.created   # <-- Add this line
    order-cancelled: order.cancelled

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Dirección del Eureka Server
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    hostname: localhost