server:
  port: 8080
  servlet:
    context-path: /

spring:
  boot:
    boot:
      admin:
        context-path: /
        ui:
          public-url: http://localhost:8080/admin
  application:
    name: admin-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true