server:
  port: 8087

spring:
  application:
    name: profile-service
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: auth-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:profile_db}?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:rootpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: TU_SECRETO_COMPARTIDO

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Dirección del Eureka Server
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    hostname: localhost
